<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link href="${pageContext.request.contextPath}/css/vitepub.css" rel="stylesheet"> 
<script src="${pageContext.request.contextPath}/js/jquery.popupoverlay.js"></script>
</head>
<body>
<jsp:include page="../navigation/topNavVitePub.jsp"/>

<div id="divmainpagewrapper">
		<table width="100%" bgcolor="#ffffff">
			<tr>

				<td>
					<table>
						<tr>
							<td style="width: 200px;">&nbsp;</td>
							<td><img
								src="${pageContext.request.contextPath}/images/user_man-128.png">
							</td>
							<td>
								<div class="welcome_identifier"
									style="font-family: Calibri; font-size: 20pt; color: #000; font-weight: bold">
									<span class="book_title"
										style="font-family: Calibri; font-size: 20pt; color: #2B3D8F; font-weight: bold">
										THE MILITARY WORLD OF MILESTOPIA </span>

								</div>
								<div class="bookshelf_text"
									style="font-family: Calibri; font-size: 16pt; color: #2B3D8F; font-weight: bold">BY
									CHRIS MILES [1 BOOK(S)]</div>
							</td>
							<td style="width: 450px" align="right">
								<table>
								   <tr>
								     <td>
								     <div>
									<span><img
										src="${pageContext.request.contextPath}/images/category.png">
										</span>
								    </div>
								    
							 
								    </td>
								    <td><span style="margin-top:0px;">SEE MORE BY AUTHOR</span> </td>
								     </tr>
								      <tr>
								     <td>
								     <div>
									<span><img
										src="${pageContext.request.contextPath}/images/category.png">
										</span>
								    </div>
								    
							 
								    </td>
								    <td><span style="margin-top:0px;">SEE MORE BY CATEGORY</span> </td>
								     </tr>
								      <tr>
								     <td>
								     <div>
									<span><img
										src="${pageContext.request.contextPath}/images/category.png">
										</span>
								    </div>
								    
							 
								    </td>
								    <td><span style="margin-top:0px;">ADD TO BOOKSHELF</span> </td>
								     </tr>
								</table>
								
								
							</td>
							
							
						</tr>
                        
                          
					</table>
				</td>
			</tr>
			<tr>
			<td> &nbsp; </td>
			</tr>
			<tr>
				
				<td>
					<table>
						<tr><td style="width: 200px;">&nbsp;</td>
						<td style="width: 50px;">&nbsp;</td>
							<td> 
								<div class="bookshelf_text"
									style="font-family: Calibri; font-size: 12pt; color: #000; font-weight: bold">
									CATEGORY: <span
										style="font-family: Calibri; font-size: 12pt; color: #2B3D8F; font-weight: bold">
										FANTASY, SCIENCE FICTION, HORROR [ 100 BOOK(S)] </span>

								</div>
							</td>
						</tr>
						<tr><td style="width: 200px;">&nbsp;</td>
						<td style="width: 50px;">&nbsp;</td>
							<td>
								<div class="bookshelf_text"
									style="font-family: Calibri; font-size: 12pt; color: #000; font-weight: bold">
									SUB-CATEGORY: <span
										style="font-family: Calibri; font-size: 12pt; color: #2B3D8F; font-weight: bold">
										SCIENCE FICTION [ 10 BOOK(S)] </span>

								</div>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			
			<tr>
			<td> <hr width="100%">
			</td>
			</tr>
			<tr>
				
				<td>
					<table>
						
						<tr><td> &nbsp; </td></tr>
						<tr><td style="width: 200px;">&nbsp;</td>
							<td colspan="2">
							    
							    <div class="bookshelf_text"
									style="font-family: Calibri; font-size: 20pt; color: #2B3D8F; font-weight: bold">
									CHAPTER 1 
								</div>
								<div><span
										style="font-family: Calibri; font-size: 10pt; color: #000; ">
										WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.  
									    WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG.WE ARE INTRODUCED TO THE MAJOR FAMILIES THROUGH THE VEHICLE OF A SOIREE AT THE ANNA PAVLOVNA'S HOME, A NAME-DAY CELEBRATION AT THE
										ROSTOVS, AND A DESCRIPTION OF THE ISOLATED EXISTENCE OF THE BOLKONSKYS AT THEIR COUNTRY SEAT, PRINCE ANDREY AND PIERRE DISCUSS THEIR FUTURES AND WHAT THEY
										SEEK IN LIDE, BOTH YOUNG MEN IDEALIZING THE "MAN OF DESTINY" WHO IS SOON TO INVADE RUSSIA. OLD COUNT BEZUHOV DIES, LEAVING PIERRE WEALTHY, TITLED, AND THE MOST ELIGIBLE BACHELOR IN PETERSBURG. </span>
									</div>
									
								 
								</td> <td>&nbsp; </td>
							
						</tr>
						<tr><td> &nbsp; </td></tr>
						<tr>
						<td> &nbsp; </td>
						  <td><a href="#"> PREVIOUS CHAPTER </a> </td> 
						  <td align="right"> <a href="#"> NEXT CHAPTER</a></tr>
					</table>
				</td>
			</tr>
		</table>
</div>
</body>
</html>